name: release
on:
  workflow_dispatch
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: centos:centos7
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.6
      - name: Check glibc version
        shell: bash
        run: ldd --version